{
 "title": "Room temperature & humidity",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Room temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "mqtt_consumer_AM2301_Temperature",
     "legendFormat": "{{ room }}"
    },
    {
     "expr": "mqtt_consumer_SI7021_Temperature",
     "legendFormat": "{{ room }}"
    }
   ]
  },
  {
   "title": "Room humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "mqtt_consumer_AM2301_Humidity", "legendFormat": "{{ room }}" },
    { "expr": "mqtt_consumer_SI7021_Humidity", "legendFormat": "{{ room }}" }
   ]
  },
  {
   "title": "Room Dew Point",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "mqtt_consumer_AM2301_DewPoint", "legendFormat": "{{ room }}" },
    { "expr": "mqtt_consumer_SI7021_DewPoint", "legendFormat": "{{ room }}" }
   ]
  },
  {
   "title": "ON/OFF status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    { "expr": "mqtt_consumer_POWER", "legendFormat": "{{ room }}" }
   ]
  }
 ]
}